---
- name: APT | Install certbot
  become: true
  become_user: root
  apt:
    name:
      - certbot

- name: APT | Install cerbot plugin
  become: true
  become_user: root
  apt:
    name:
      - python-certbot-{{ ssl_webserver }}
  when: ssl_webserver in ["apache", "nginx"]
